name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache node_modules for faster installs
      - name: Cache node_modules
        uses: actions/cache@v4.1.2
        with:
          path: ~/.npm # If using npm
          # For yarn, use path: ~/.cache/yarn
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image with environment variables
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react:v1 \
            --build-arg NEXT_PUBLIC_SPRING_API_URL=${{ secrets.NEXT_PUBLIC_SPRING_API_URL }} \
            --build-arg NEXT_PUBLIC_FAST_API_URL=${{ secrets.NEXT_PUBLIC_FAST_API_URL }} .

      # Push the Docker image
      - name: Push Docker image
        run: |
          docker push "${{ secrets.DOCKER_USERNAME }}/react:v1"
